// import './globals.css'

import Navbar from '@/component/navbar'
// import { Inter } from 'next/font/google'
import Divider from '@mui/material/Divider';
// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
      <Divider/>
     
      {children}</body>
    </html>
  )
}
