// import './globals.css'
import Navbar from '@/component/navbar'
import { Suspense } from 'react'

// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
import Loading from './loading'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
 
  return (
    <html lang="en">

      <body ><Suspense fallback={<Loading/>}><Navbar/>{children}</Suspense></body>
    </html>
  )
}
